[package]
name = "rlox-parser"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlox-contract = { path = "../rlox-contract" }
log = "0.4.14"